 
// This file was generated by the script 'generate-openapi-types.mjs'. Don't modify it manually!

export interface paths {
  '/example-custom-endpoint/{pathParam}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          pathParam: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['GeneratedExampleCustomEndpointPathParamGetOk'];
          };
        };
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['GeneratedExampleCustomEndpointPathParamGetErr'];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query: {
          userId: string;
        };
        header?: never;
        path: {
          pathParam: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['GeneratedExampleCustomEndpointPathParamPostBody'];
        };
      };
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['GeneratedExampleCustomEndpointPathParamPostOk'];
          };
        };
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['GeneratedExampleCustomEndpointPathParamPostErr'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    GeneratedExampleCustomEndpointPathParamPostQuery: {
      userId: string;
    };
    GeneratedExampleCustomEndpointPathParamPostBody: {
      name: string;
      age?: number;
    };
    GeneratedExampleCustomEndpointPathParamPostOk: {
      user: string;
      id: string;
      age?: number;
      description: string;
    };
    GeneratedExampleCustomEndpointPathParamPostErr: {
      errorMsg: string;
      errorCode: number;
    };
    GeneratedExampleCustomEndpointPathParamGetOk: {
      id: string;
      name: string;
    };
    GeneratedExampleCustomEndpointPathParamGetErr: {
      errorMsg: string;
      errorCode: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
