// This file was auto-generated by generate-openapi-types.mjs. Don't modify it manually!
// EsLint disable reason: We want to keep the original naming from the OpenAPI spec for clarity and consistency.

import type * as S0 from './customApiSchema';

type ComponentsFinal = S0.components;
type DefsFinal = S0.$defs;
type PathsFinal = S0.paths;
type WebhooksFinal = S0.webhooks;
type OperationsFinal = S0.operations;

/**
 * Final exported types combining all schemas. These types represent the complete OpenAPI schema
 * by merging paths, webhooks, components, $defs, and operations from all individual schemas.
 */
export type components = ComponentsFinal;
export type $defs = DefsFinal;
export type paths = PathsFinal;
export type webhooks = WebhooksFinal;
export type operations = OperationsFinal;
